name: Builds

on:
  push: { branches: [main] }
  pull_request:
    paths-ignore:
      - '.github/**'

env:
  UNITY_LICENSE:
<?xml version="1.0" encoding="UTF-8"?><root>
    <License id="Terms">
        <MachineBindings>
            <Binding Key="1" Value="576562626572264761624c65526f7578"/>
            <Binding Key="2" Value="576562626572264761624c65526f7578"/>
        </MachineBindings>
        <MachineID Value="D7nTUnjNAmtsUMcnoyrqkgIbYdM="/>
        <SerialHash Value="0cfda3fbdb3ae0c7a47879890dbc42bd67ea2fb0"/>
        <Features>
            <Feature Value="33"/>
            <Feature Value="1"/>
            <Feature Value="12"/>
            <Feature Value="2"/>
            <Feature Value="24"/>
            <Feature Value="3"/>
            <Feature Value="36"/>
            <Feature Value="17"/>
            <Feature Value="19"/>
            <Feature Value="62"/>
        </Features>
        <DeveloperData Value="AQAAAEY0LUozTlktMlVVVy0yREtXLUtOS1MtTjhSRQ=="/>
        <SerialMasked Value="F4-J3NY-2UUW-2DKW-KNKS-XXXX"/>
        <StartDate Value="2022-11-14T00:00:00"/>
        <UpdateDate Value="2023-01-14T18:49:51"/>
        <InitialActivationDate Value="2022-11-14T12:24:18"/>
        <LicenseVersion Value="6.x"/>
        <ClientProvidedVersion Value="2019.2.11f1"/>
        <AlwaysOnline Value="false"/>
        <Entitlements>
            <Entitlement Ns="unity_editor" Tag="UnityPersonal" Type="EDITOR" ValidTo="9999-12-31T00:00:00"/>
            <Entitlement Ns="unity_editor" Tag="DarkSkin" Type="EDITOR_FEATURE" ValidTo="9999-12-31T00:00:00"/>
        </Entitlements>
    </License>
<Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments"/><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><Reference URI="#Terms"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><DigestValue>uOodCs4DA02VwlFsvb6rD+1ti8Q=</DigestValue></Reference></SignedInfo><SignatureValue>l7OjojUccFAkyMxqLOrn7pZeC88naQLHvYtrAopExuwxKJGvzwoXXHGBFcSq1WgH9UiaoqTz5ZRL&#13;
6xH5p+8I634Uw4kFVrK9skiCkueuxwzHunPC+oK5EhOKRvS2FFN+Pwfh6ydOPqPwNwFyvtFQbeyA&#13;
IRNLq5M/GluDaL4C1YcrzNIbWUtepe7lLmdPjSSd6FLaEUpmW97CIdG+wZsdRbpYRozduhA3PXZP&#13;
BLEE2Rd8OC5bCR23wPtXeZIDbQUevxyk+2WAHiewVU/OXZREoXV8Et4VmPCqNGdcJP7lTO2rHq3K&#13;
ee5RXDv3ZzfwVcXrMiR8+uJoDuwdRn6O4mB+Pg==</SignatureValue></Signature></root>

jobs:
  buildForAllPlatformsUbuntu:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cloudRunnerCluster:
          # - local-docker
          - local
        projectPath:
          - TRSRB
        unityVersion:
          - 2021.3.13f1
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
          - iOS # Build an iOS player.
          - Android # Build an Android .apk.
          - WebGL # WebGL.
          #          - StandaloneWindows # Build a Windows standalone.
          #          - WSAPlayer # Build an Windows Store Apps player.
          #          - PS4 # Build a PS4 Standalone.
          #          - XboxOne # Build a Xbox One Standalone.
          #          - tvOS # Build to Apple's tvOS platform.
          #          - Switch # Build a Nintendo Switch player
    steps:
      ###########################
      #         Checkout        #
      ###########################
      - uses: actions/checkout@v2
        with:
          lfs: true

      ###########################
      #          Cache          #
      ###########################
      - uses: actions/cache@v2
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-ubuntu-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-ubuntu-
            Library-
      ###########################
      #          Build          #
      ###########################
      - uses: ./
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          customParameters: -profile SomeProfile -someBoolean -someValue exampleValue
          cloudRunnerCluster: ${{ matrix.cloudRunnerCluster }}

      ###########################
      #          Upload         #
      ###########################
      - uses: actions/upload-artifact@v2
        with:
          name: Build Ubuntu (${{ matrix.unityVersion }})
          path: build
          retention-days: 14